In [1]:
import numpy as np

In [2]:
relations = {(0, 1), (0, 2), (1, 2), (1, 3), (1, 0), (1, 4), (1, 5), (2, 1), (2, 0), (2, 6), (2, 5), 
             (3, 1), (3, 4), (4, 3), (4, 5), (4, 7), (4, 1), (5, 1), (5, 2), (5, 6), (5, 7), (5, 8), 
             (5, 9), (5, 10), (6, 5), (6, 11), (6, 13), (7, 8), (7, 5), (7, 4), (8, 5), (8, 7), (8, 9), 
             (9, 8), (9, 10), (9, 5), (9, 13), (9, 14), (10, 5), (10, 9), (10, 12), (10, 13), (11, 6), 
             (11, 12), (12, 10), (12, 11), (12, 13), (12, 21), (12, 18), (12, 19), (12, 23), (12, 24), 
             (13, 9), (13, 10), (13, 12), (13, 14), (13, 15), (13, 16), (13, 18), (14, 9), (14, 13), 
             (14, 31), (14, 30), (15, 13), (15, 17), (15, 31), (16, 13), (16, 17), (16, 18), (17, 16), 
             (17, 15), (17, 19), (17, 18), (17, 20), (18, 13), (18, 12), (18, 16), (18, 17), (18, 19), 
             (19, 12), (19, 17), (19, 18), (19, 24), (19, 24), (19, 20), (19, 21), (20, 17), (20, 19), 
             (20, 22), (20, 25), (20, 29), (20, 31), (20, 27), (21, 13), (21, 12), (21, 19), (21, 23), 
             (21, 24), (22, 20), (22, 23), (22, 24), (23, 19), (23, 21), (23, 24), (23, 22), (24, 12), 
             (24, 23), (24, 22), (24, 21), (24, 25), (25, 20), (24, 24), (25, 26), (25, 27), (26, 25), 
             (26, 27), (27, 25), (27, 20), (27, 29), (27, 28), (27, 26), (28, 27), (28, 29), (28, 30), 
             (29, 27), (29, 28), (29, 30), (29, 31), (29, 20), (30, 14), (30, 28), (30, 29), (31, 14), 
             (31, 15), (31, 29), (31, 20)}

In [3]:
n = max(max(pair) for pair in relations) + 1

In [4]:
adj_matrix = np.zeros((n, n), dtype=int)

In [5]:
for i, j in relations:
    adj_matrix[i, j] = 1

In [6]:
np.set_printoptions(threshold=np.inf)
print(adj_matrix)

[[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 